# Generated by Django 5.2 on 2025-04-14 14:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("MS", "0002_rating_thrift_alter_rating_product_alter_rating_user_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="chat",
            name="thrift",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="chats",
                to="MS.thriftproduct",
            ),
            preserve_default=False,
        ),
    ]
