# Generated by Django 5.2 on 2025-04-14 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("MS", "0003_chat_thrift"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="type",
            field=models.CharField(
                choices=[("chat", "Chat"), ("alert", "Alert")],
                default="alert",
                max_length=20,
            ),
        ),
    ]
