# Generated by Django 5.2 on 2025-04-15 04:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("MS", "0004_notification_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="notification",
            name="created_at",
        ),
        migrations.AddField(
            model_name="notification",
            name="timestamp",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="notification",
            name="message",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="notification",
            name="type",
            field=models.CharField(default="general", max_length=50),
        ),
    ]
