# Generated by Django 5.2 on 2025-04-16 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("MS", "0007_biddingproduct_notified"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="age_group",
            field=models.CharField(
                choices=[
                    ("0-3", "0-3 Years"),
                    ("4-7", "4-7 Years"),
                    ("8-10", "8-10 Years"),
                    ("11-14", "11-14 Years"),
                ],
                default="8-10",
                max_length=10,
            ),
        ),
    ]
