# Generated by Django 5.2 on 2025-04-16 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("MS", "0008_product_age_group"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="customuser",
            name="logo",
            field=models.ImageField(blank=True, null=True, upload_to="vendor_logos/"),
        ),
        migrations.AddField(
            model_name="customuser",
            name="store_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="age_group",
            field=models.CharField(
                choices=[
                    ("8-10", "8-10 Years"),
                    ("11-14", "11-14 Years"),
                    ("15-17", "15-17 Years"),
                    ("18-19", "18-19 Years"),
                    ("20-24", "20-24 Years"),
                    ("25-29", "25-29 Years"),
                    ("30-34", "30-34 Years"),
                    ("35-39", "35-39 Years"),
                ],
                default="8-10",
                max_length=10,
            ),
        ),
    ]
