# Generated by Django 5.2 on 2025-04-16 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("MS", "0009_customuser_description_customuser_logo_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="payment_method",
            field=models.CharField(
                choices=[("COD", "Cash on Delivery"), ("eSewa", "eSewa")],
                default="COD",
                max_length=20,
            ),
        ),
    ]
