# Generated by Django 5.2 on 2025-04-20 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("MS", "0011_profile"),
    ]

    operations = [
        migrations.AddField(
            model_name="cartitem",
            name="size",
            field=models.CharField(default="M", max_length=10),
        ),
    ]
