# Generated by Django 5.2 on 2025-04-20 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("MS", "0012_cartitem_size"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="age_group",
            field=models.CharField(
                choices=[
                    ("8-10", "8-10 Years"),
                    ("11-14", "11-14 Years"),
                    ("15-17", "15-17 Years"),
                    ("18-19", "18-19 Years"),
                    ("20-24", "20-24 Years"),
                    ("25-29", "25-29 Years"),
                    ("30-34", "30-34 Years"),
                    ("35-39", "35-39 Years"),
                ],
                default="8-10",
                max_length=20,
            ),
        ),
    ]
