# Generated by Django 5.2 on 2025-04-20 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("MS", "0013_alter_product_age_group"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="age_group",
            field=models.CharField(default="8-10", max_length=20),
        ),
    ]
