# Generated by Django 5.2 on 2025-04-20 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("MS", "0014_alter_product_age_group"),
    ]

    operations = [
        migrations.CreateModel(
            name="AgeGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name="Size",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name="product",
            name="is_thrift",
        ),
        migrations.RemoveField(
            model_name="product",
            name="age_group",
        ),
        migrations.RemoveField(
            model_name="product",
            name="size",
        ),
        migrations.AddField(
            model_name="product",
            name="age_group",
            field=models.ManyToManyField(to="MS.agegroup"),
        ),
        migrations.AddField(
            model_name="product",
            name="size",
            field=models.ManyToManyField(to="MS.size"),
        ),
    ]
