# Generated by Django 5.2 on 2025-04-20 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("MS", "0015_agegroup_size_remove_product_is_thrift_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="agegroup",
            name="label",
            field=models.CharField(max_length=100),
        ),
    ]
