# Generated by Django 5.2 on 2025-04-26 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("MS", "0016_alter_agegroup_label"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="age_group",
        ),
        migrations.AddField(
            model_name="product",
            name="age_group",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
